CREATE DATABASE `shipmentdb` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

CREATE TABLE `PACKETS` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NAME` varchar(50) NOT NULL,
  `SENDER_ID` int NOT NULL,
  `RECEIVER_ID` int NOT NULL,
  `WEIGHT` decimal(5,2) NOT NULL,
  `BUSINESS_ID` varchar(37) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `SENDER_ID` (`SENDER_ID`),
  KEY `RECEIVER_ID` (`RECEIVER_ID`),
  KEY `BUSINESS_ID` (`BUSINESS_ID`),
  CONSTRAINT `PACKETS_ibfk_1` FOREIGN KEY (`SENDER_ID`) REFERENCES `SENDERS` (`ID`),
  CONSTRAINT `PACKETS_ibfk_2` FOREIGN KEY (`RECEIVER_ID`) REFERENCES `RECIPIENTS` (`ID`),
  CONSTRAINT `PACKETS_ibfk_3` FOREIGN KEY (`BUSINESS_ID`) REFERENCES `PARTNER_BUSINESSES` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `PARTNER_BUSINESSES` (
  `ID` varchar(40) NOT NULL,
  `NAME` varchar(20) NOT NULL,
  `SENDER_ADDRESS_ID` int NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `SENDER_ADDRESS_ID` (`SENDER_ADDRESS_ID`),
  CONSTRAINT `PARTNER_BUSINESSES_ibfk_1` FOREIGN KEY (`SENDER_ADDRESS_ID`) REFERENCES `SENDERS` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `RECIPIENTS` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NAME` varchar(50) NOT NULL,
  `ADDRESS_1` varchar(45) NOT NULL,
  `ADDRESS_2` varchar(45) DEFAULT NULL,
  `CITY` varchar(45) NOT NULL,
  `STATE` varchar(45) NOT NULL,
  `ZIP` varchar(7) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `SENDERS` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NAME` varchar(50) NOT NULL,
  `ADDRESS` varchar(45) NOT NULL,
  `CITY` varchar(45) NOT NULL,
  `STATE` varchar(45) NOT NULL,
  `ZIP` varchar(7) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

